services:
  ozean12_google_pubsub.pubsub_client.service:
    class: Google\Cloud\PubSub\PubSubClient
    public: false
    arguments:
      - # config

  ozean12_google_pubsub.client.service:
    class: Ozean12\GooglePubSubBundle\Service\AbstractClient
    public: false
    arguments:
      - # topic or subscription
      - # client
      - "@jms_serializer"
      - # suffix

  ozean12_google_pubsub.push_subscriber_manager.service:
    class: Ozean12\GooglePubSubBundle\Service\Subscriber\PushSubscriberManager
    arguments:
      - # project id
      - "%env_suffix%"
